# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OPTIMAL-IPB
                                 A QGIS plugin
 This plugin adds an algorithm to calculate palm tree on high resolution imagery based on machine learning
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-22
        copyright            : (C) 2020 by Muhammad Nurdin
        email                : muhanur@apps.ipb.ac.id
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Muhammad Nurdin'
__date__ = '2020-09-22'
__copyright__ = '(C) 2020 by Muhammad Nurdin'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OPTIMAL-IPB class from file OPTIMAL-IPB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .optimal_ipb import OptimalIpbPlugin
    return OptimalIpbPlugin(iface)
